GYM:
    AUTO_NAME: "NavToObj"
    OBS_KEYS: ["robot_head_depth", "object_to_agent_gps_compass", 'joint', 'nav_to_skill']
    CLASS_NAME: "RearrangeRLEnv"
ENVIRONMENT:
    MAX_EPISODE_STEPS: 400
DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/datasets/replica_cad/rearrange/v1/{split}/all_receptacles_10k_1k.json.gz
    SCENES_DIR: "data/replica_cad/"
TASK:
    TYPE: RearrangeNavToObjTask-v0

    MUST_LOOK_AT_TARG: True
    CONSTRAINT_VIOLATION_ENDS_EPISODE: False
    # If true, will always regenerate the cache
    FORCE_REGENERATE: False
    DESIRED_RESTING_POSITION: [0.5, 0.0, 1.0]
    OBJECT_IN_HAND_SAMPLE_PROB: 0.167

    # Collision related
    COUNT_OBJ_COLLISIONS: True
    COUNT_ROBOT_OBJ_COLLS: False
    MAX_COLLISIONS: -1.0

    FILTER_NAV_TO_TASKS: []

    # PDDL related parameters
    PDDL_DOMAIN_DEF: "configs/tasks/rearrange/pddl/replica_cad_domain.yaml"
    OBJ_SUCC_THRESH: 0.3
    ART_SUCC_THRESH: 0.15

    REWARD_MEASURE: "nav_to_obj_reward"
    SUCCESS_MEASURE: "nav_to_obj_success"
    SUCCESS_REWARD: 10.0
    SLACK_REWARD: 0.0
    END_ON_SUCCESS: True

    TARGET_START_POINT_GOAL_SENSOR:
        TYPE: "TargetOrGoalStartPointGoalSensor"
    NAV_TO_SKILL_SENSOR:
        TYPE: "NavToSkillSensor"
        NUM_SKILLS: 8
    JOINT_SENSOR:
        TYPE: "JointSensor"
        DIMENSIONALITY: 7
    SENSORS: ["TARGET_START_POINT_GOAL_SENSOR", "JOINT_SENSOR", "NAV_TO_SKILL_SENSOR"]

    ROBOT_FORCE:
        TYPE: "RobotForce"
        MIN_FORCE: 20.0
    FORCE_TERMINATE:
        TYPE: "ForceTerminate"
        MAX_ACCUM_FORCE: -1.0
    ROBOT_COLLS:
        TYPE: "RobotCollisions"
    OBJECT_TO_GOAL_DISTANCE:
        TYPE: "ObjectToGoalDistance"
    ROT_DIST_TO_GOAL:
        TYPE: "RotDistToGoal"
    DIST_TO_GOAL:
        TYPE: "DistToGoal"
    BAD_CALLED_TERMINATE:
        TYPE: "BadCalledTerminate"
        BAD_TERM_PEN: 0.0
        DECAY_BAD_TERM: False
    NUM_STEPS:
        TYPE: "NumStepsMeasure"
    REARRANGE_NAV_TO_OBJ_REWARD:
        TYPE: "NavToObjReward"
        # Reward the agent for facing the object?
        SHOULD_REWARD_TURN: True
        # What distance do we start giving the reward for facing the object?
        TURN_REWARD_DIST: 0.6
        # Multiplier on the angle distance to the goal.
        ANGLE_DIST_REWARD: 1.0
        DIST_REWARD: 10.0

        # General Rearrange Reward config
        CONSTRAINT_VIOLATE_PEN: 10.0
        FORCE_PEN: 0.0
        MAX_FORCE_PEN: 1.0
        FORCE_END_PEN: 5.0
    NAV_TO_POS_SUCC:
        TYPE: "NavToPosSucc"
        SUCCESS_DISTANCE: 0.3
    REARRANGE_NAV_TO_OBJ_SUCCESS:
        TYPE: "NavToObjSuccess"
        MUST_LOOK_AT_TARG: True
        # Distance in radians.
        SUCCESS_ANGLE_DIST: 0.3
        HEURISTIC_STOP: False
    MEASUREMENTS:
        - "OBJECT_TO_GOAL_DISTANCE"
        - "ROBOT_FORCE"
        - "FORCE_TERMINATE"
        - "ROBOT_COLLS"
        - "ROT_DIST_TO_GOAL"
        - "DIST_TO_GOAL"
        - "NAV_TO_POS_SUCC"
        - "REARRANGE_NAV_TO_OBJ_SUCCESS"
        - "BAD_CALLED_TERMINATE"
        - "REARRANGE_NAV_TO_OBJ_REWARD"
        - "NUM_STEPS"
    ACTIONS:
      BASE_VELOCITY:
        TYPE: "BaseVelAction"
        LIN_SPEED: 15.0
        ANG_SPEED: 15.0
        ALLOW_DYN_SLIDE: True
        ALLOW_BACK: True
        END_ON_STOP: True
        MIN_ABS_LIN_SPEED: 1.0
        MIN_ABS_ANG_SPEED: 1.0
    POSSIBLE_ACTIONS: ['BASE_VELOCITY']

SIMULATOR:
    ADDITIONAL_OBJECT_PATHS:
        - "data/objects/ycb/configs/"
    ACTION_SPACE_CONFIG: v0
    DEBUG_RENDER: False
    DEBUG_RENDER_GOAL: True
    CONCUR_RENDER: True
    AUTO_SLEEP: True

    AGENTS: ['AGENT_0']
    AGENT_0:
        HEIGHT: 1.5
        RADIUS: 0.3
        SENSORS: ['HEAD_DEPTH_SENSOR']
    HEAD_RGB_SENSOR:
        WIDTH: 128
        HEIGHT: 128
    HEAD_DEPTH_SENSOR:
        WIDTH: 128
        HEIGHT: 128
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: True
    ARM_DEPTH_SENSOR:
        HEIGHT: 128
        MAX_DEPTH: 10.0
        MIN_DEPTH: 0.0
        NORMALIZE_DEPTH: True
        WIDTH: 128
    ARM_RGB_SENSOR:
        HEIGHT: 128
        WIDTH: 128

    # Agent setup
    ARM_REST: [0.6, 0.0, 0.9]
    CTRL_FREQ: 120.0
    AC_FREQ_RATIO: 4
    ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_fetch.urdf
    ROBOT_TYPE: "FetchRobot"
    FORWARD_STEP_SIZE: 0.25

    # Grasping
    HOLD_THRESH: 0.09
    GRASP_IMPULSE: 1000.0

    DEFAULT_AGENT_ID: 0
    HABITAT_SIM_V0:
        ALLOW_SLIDING: false
        ENABLE_PHYSICS: True
        GPU_DEVICE_ID: 0
        GPU_GPU: False
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    SEED: 100
    SEMANTIC_SENSOR:
        HEIGHT: 480
        HFOV: 90
        ORIENTATION: [0.0, 0.0, 0.0]
        POSITION: [0, 1.25, 0]
        TYPE: HabitatSimSemanticSensor
        WIDTH: 640
    TILT_ANGLE: 15
    TURN_ANGLE: 10
    TYPE: RearrangeSim-v0
